#!/usr/bin/perl

use strict;
use warnings;

my $file = shift @ARGV;

open my $pipeh, "|-", "gnuplot", "--persist" or
   die "Cannot popen gnuplot - $!";

my @plots = (
   ' using 1:3 title "p10" with line',
   ' using 1:4 title "p25" with line',
   ' using 1:5 title "p50" with line linewidth 2',
   ' using 1:6 title "p75" with line',
   ' using 1:7 title "p90" with line',
);

my $PLOTS = join( ", ", map { qq("$file"$_) } @plots );

print $pipeh <<"EOF";
set title "$file"
set xlabel "Messages"
set ylabel "Latency, seconds"

plot $PLOTS
EOF
